### ISSUE TITLE
BMC network interface has NO AUTHENTICATION, no TLS

### ISSUE THREAD

**Issue by CFSworks** [turing-machines/turing-pi#11]
I'm sure this one is on the roadmap already, but it should be documented with an issue nonetheless.

The BMC's security situation is currently abysmal as anyone on the same network (or who has perhaps intruded into one of the nodes) can control it without any authentication. Even with authentication, the lack of TLS means that an attacker can just sniff the credentials off of the network (perhaps with the aid of a MITM attack) when the authorized sysadmin logs in.

Access to the BMC's API by an unauthorized attacker could prove disastrous if that API eventually allows unrestricted access to each node's eMMC.

**Comment by svenrademakers** [comment]
There is a new HTTP interface on the horizon (which will have proper authentication), i therefore don't want to spend too much time on the current one.
