### ISSUE TITLE
Device tree has unnecessary device nodes

### ISSUE THREAD

**Issue by CFSworks** [turing-machines/turing-pi#5]
There are several nodes in the devicetree that are not used in this application. The following should probably be removed:

- `codec`
- `daudio`
- `deinterlace`
- `disp`
- `dmic`
- `hdmi`
- `hdmiaudio`
- `ir`
- `keyboard`
- `lcd0`
- `lcd_fb0`
- `rtp`
- `sound`
- `sounddaudio0`, `sounddaudio1`, `sounddaudio2`
- `sounddmic`
- `soundspdif`
- `spdif`
- `tv0`
- `tvd0`
- `tvd`
- `ve`

These are pretty much all related to media and human-interaction use cases, and appear to be holdovers from the 100ask dev board configuration. Removing them should somewhat improve boot time and reduce memory usage.

**Comment by svenrademakers** [comment]
Verified the devices. i agree with the poster. devices can be removed from the dts config. 
Issue can be picked up
